substitutions:
  device_name: above_entry
  voltage_name: "Above Entry Voltage"
  voltage_divider: '2030'
  power_name: "Above Entry Usage"
  current_name: "Above Entry Current"
  current_resistor: '0.00227'

<<: !include common/common_config.yaml

<<: !include devices/kogan_smart_plug_with_energy_meter.yaml
