esphome:
  name: extension_cord
  comment: https://www.bunnings.com.au/arlec-grid-connect-smart-10m-extension-lead_p0098824
  platform: ESP8266
  board: esp8285

<<: !include common/common_config.yaml

<<: !include devices/arlec_extension_cord.yaml