esphome:
  name: power_board
  comment: https://www.bunnings.com.au/arlec-grid-connect-smart-4-outlet-powerboard-with-usb-charger_p0074829
  platform: ESP8266
  board: esp8285

<<: !include common/common_config.yaml

<<: !include devices/arlec_4_point_power_board.yaml