esphome:
  name: testpower2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "ESPHome"
  password: "ESPHome"
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "ESPHome"

ota:
  password: "ESPHome"

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      inverted: True
    name: "Left Button"
    on_press:
      - switch.toggle: Left_Relay
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Right Button"
    on_press:
      - switch.toggle: Right_Relay
output:
- platform: gpio
  pin: GPIO14
  inverted: True
  id: Left_LED
- platform: gpio
  pin: GPIO0
  inverted: True
  id: Right_LED

switch:
- platform: gpio
  name: "Left Relay"
  pin: GPIO13
  restore_mode: ALWAYS_OFF
  id: Left_Relay
  on_turn_on:
    - output.turn_on: Left_LED
  on_turn_off:
    - output.turn_off: Left_LED
- platform: gpio
  name: "Right Relay"
  pin: GPIO15
  restore_mode: ALWAYS_OFF
  id: Right_Relay
  on_turn_on:
    - output.turn_on: Right_LED
  on_turn_off:
    - output.turn_off: Right_LED
- platform: gpio
  name: "Enable Buttons"
  pin: GPIO3
  restore_mode: ALWAYS_ON

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO5
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    voltage_divider: 100000
    current_resistor: 1.1
    current:
      name: "Amperage"
      unit_of_measurement: A
    voltage:
      name: "Voltage"
      unit_of_measurement: V
    power:
      name: "Wattage"
      unit_of_measurement: W
      id: "Wattage"
    change_mode_every: 8
    update_interval: 10s