esphome:
  name: $device_name
  comment: https://www.bunnings.com.au/arlec-grid-connect-smart-10m-extension-lead_p0098824
  platform: ESP8266
  board: esp8285

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: Relay

output:
- platform: gpio
  pin: GPIO13
  inverted: True
  id: LED

switch:
- platform: gpio
  name: "Relay"
  pin: GPIO14
  restore_mode: RESTORE_DEFAULT_OFF
  id: Relay
  on_turn_on:
    - output.turn_on: LED
  on_turn_off:
    - output.turn_off: LED