binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: Relay

output:
- platform: gpio
  pin: GPIO13
  inverted: True
  id: LED

switch:
- platform: gpio
  name: "Relay"
  pin: GPIO14
  restore_mode: RESTORE_DEFAULT_OFF
  id: Relay
  on_turn_on:
    - output.turn_on: LED
  on_turn_off:
    - output.turn_off: LED