esphome:
  name: $device_name
  comment: https://www.bunnings.com.au/arlec-grid-connect-smart-4-outlet-powerboard-with-usb-charger_p0074829
  platform: ESP8266
  board: esp8285

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: True
    name: "Button"
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - if: 
            condition:
              lambda: 'return id(MasterSwitch).state == true;'
            then:
              - switch.turn_off: Relay_1
              - delay: 150ms
              - switch.turn_off: Relay_2
              - delay: 150ms
              - switch.turn_off: Relay_3
              - delay: 150ms
              - switch.turn_off: Relay_4
              - delay: 150ms
            else:
              - switch.turn_on: Relay_1
              - delay: 150ms
              - switch.turn_on: Relay_2
              - delay: 150ms
              - switch.turn_on: Relay_3
              - delay: 150ms
              - switch.turn_on: Relay_4
              - delay: 150ms
  - platform: template
    name: "Master Switch"
    id: MasterSwitch
    lambda: |-
      if(id(Relay_1).state || id(Relay_2).state || id(Relay_3).state || id(Relay_4).state) {
        return true;
      } else {
        return false;
      }
    on_release:
      - output.turn_off: LED
    on_press:
      - output.turn_on: LED

output:
- platform: gpio
  pin: GPIO01
  inverted: True
  id: LED

switch:
- platform: gpio
  name: "Port 1"
  pin: GPIO05
  restore_mode: RESTORE_DEFAULT_OFF
  id: Relay_1
- platform: gpio
  name: "Port 2"
  pin: GPIO04
  restore_mode: RESTORE_DEFAULT_OFF
  id: Relay_2
- platform: gpio
  name: "Port 3"
  pin: GPIO13
  restore_mode: RESTORE_DEFAULT_OFF
  id: Relay_3
- platform: gpio
  name: "Port 4"
  pin: GPIO12
  restore_mode: RESTORE_DEFAULT_OFF
  id: Relay_4