binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      inverted: True
    name: "Left Button"
    on_press:
      - switch.toggle: Left_Relay
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Right Button"
    on_press:
      - switch.toggle: Right_Relay

output:
- platform: gpio
  pin: GPIO14
  inverted: True
  id: Left_LED
- platform: gpio
  pin: GPIO0
  inverted: True
  id: Right_LED
  
light:
- platform: binary
  name: "Left LED"
  output: Left_LED
  id: Left_LED_Switch
- platform: binary
  name: "Right LED"
  output: Right_LED
  id: Right_LED_Switch

switch:
- platform: gpio
  name: "Left Relay"
  pin: GPIO13
  restore_mode: RESTORE_DEFAULT_OFF
  id: Left_Relay
  on_turn_on:
    - light.turn_on: Left_LED_Switch
  on_turn_off:
    - light.turn_off: Left_LED_Switch
- platform: gpio
  name: "Right Relay"
  pin: GPIO15
  restore_mode: RESTORE_DEFAULT_OFF
  id: Right_Relay
  on_turn_on:
    - light.turn_on: Right_LED_Switch
  on_turn_off:
    - light.turn_off: Right_LED_Switch
- platform: gpio
  name: "Enable Buttons"
  pin: GPIO3
  inverted: False
  restore_mode: ALWAYS_ON

#sensor:
#  - platform: hlw8012
#    sel_pin:
#      number: GPIO5
#      inverted: True
#    cf_pin: GPIO04
#    cf1_pin: GPIO05
#    voltage_divider: 970000
#    current_resistor: 1.1
#    current:
#      name: "Amperage"
#      unit_of_measurement: A
#    voltage:
#      name: "Voltage"
#      unit_of_measurement: V
#    power:
#      name: "Wattage"
#      unit_of_measurement: W
#      id: "Wattage"
#    change_mode_every: 8
#    update_interval: 10s