esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285
  comment: Aldi

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 10ms
    name: "Button"
    on_press:
      - switch.toggle: Relay

output:
  - platform: gpio
    pin: GPIO13
    inverted: True
    id: LED

switch:
- platform: gpio
  name: "Relay"
  pin: GPIO14
  restore_mode: RESTORE_DEFAULT_OFF
  id: Relay
  on_turn_on:
    - output.turn_on: LED
  on_turn_off:
    - output.turn_off: LED
