esphome:
  name: $device_name
  platform: ESP8266
  board: esp01_1m

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  id: tuya_mcu

tuya:

light:
  - platform: "tuya"
    name: "Light"
    dimmer_datapoint: 2
    switch_datapoint: 1