wifi: !include wifi.yaml

web_server: 
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

captive_portal:

logger:
  level: NONE
  baud_rate: 0

api:
  password: !secret api_password

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Australia/Melbourne